name: cdc_bottlenecks

dependencies:
    - python==3.7.3
    - scipy==1.1.0
    - lxml==4.2.4
    - six==1.11.0
    - path.py
    - python-dateutil==2.7.3
    - tensorflow==1.14.0
    - cloudpickle==0.5.3
    - setuptools==39.1.0
    - pip:
        - numpy==1.17.1
        - gym==0.10.5
        - pandas
        - pyprind==2.11.2
        - nose2==0.8.0
        - cached_property
        - joblib==0.10.3
        - dill
        - lz4
        - ray==0.7.4
        - setproctitle
        - psutil
        - opencv-python
        - boto3==1.4.8
        - redis~=2.10.6
        - matplotlib==3.0.0
        - tensorflow-probability==0.7.0
        - ipdb
